### ISSUE TITLE
Certificate validation issues

### ISSUE THREAD

**Issue by Mr-iX** [microsoft/AzureFunctionforSplunkVS#20]
I always get the error 
```
The remote certificate is invalid according to the validation procedure.
```

I left the thumbprint emty, but even when specifying the correct thumbprint it does not work.

Has anyone a idea, why this doesn't work?

**Comment by cocallaw** [comment]
Have you validated the certificate that is presented when you go to the HEC endpoint (eg https://splunk.something.com:8088/services/collector) that you have set as the splunkAddress app settings value from a web browser? 

Also are you going through a proxy or any other network device to reach your Splunk instance ?

**Comment by Mr-iX** [comment]
I will check that later.

The strange thing is it worked for some time, but after deleting the function and recreating it, it stopped working.

Yes, the function is integrated into a vnet, which is connected via a VPN tunnel to our on premise network.

**Comment by Mr-iX** [comment]
@cocallaw I checked and noticed that the certificate is normally presented at the url you proposed.

**Comment by sebastus** [comment]
fixed via PR#22

**Comment by Mr-iX** [comment]
@sebastus 
Now I got this error:
`Microsoft.Azure.WebJobs.Host: Error indexing method 'FaultProcessor'. Microsoft.Azure.WebJobs.Host: '%output-hub-name-proxy%' does not resolve to a value.`


After defining this parameter in the application settings, I get this error:
```
The following 6 functions are in error:
EhActivityLogsExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhActivityLogsExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
EhDiagnosticLogsExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhDiagnosticLogsExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
EhLadTelemetryExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhLadTelemetryExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
EhMetricsExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhMetricsExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
EhWadTelemetryExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhWadTelemetryExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
FaultProcessor: Microsoft.Azure.WebJobs.Host: Error indexing method 'FaultProcessor'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
```
